### ISSUE TITLE
Update package.json and publish completed build to NPM

### ISSUE THREAD

**Issue by jasonwebb** [Accessible360/accessible-slick#3]
- [x] Set up official user account on npmjs.org.
- [x] Update `package.json` metadata file.
- [x] Publish as an NPM package.
  - [x] Set up Github Action workflow to publish to npm when a release is published.
- [x] Create a Release on Github.

**Comment by agentcap** [comment]
Hi! Can I know when this package is planned to be published to NPM? Thanks!

**Comment by jasonwebb** [comment]
Hey @agentcap! This package will be published to NPM as soon as it has been tested by expert users with disabilities as part of issue #21. My team at @Accessible360 is currently focused on a heavy end-of-year workload as our clients are rushing to hit their 2020 targets, but after New Years I expect their availability to open up.

I would estimate that this package will be officially published **before the end of January 2021**.

**Comment by jasonwebb** [comment]
Testing has been completed with a native screen reader user, and I've finished making some small updates based on their feedback (see #21). This is now ready to officially launch!

I've created a [Github workflow](https://github.com/Accessible360/accessible-slick/blob/master/.github/workflows/npm-publish.yml) to publish to both npm and Github Packages registry when a new release is published.

Now I'm trying to figure out how to set up the credentials and tokens properly, which is a little more complicated since there is an org account involved.

**Comment by jasonwebb** [comment]
While doing some dry runs, I learned that NPM requires strict semver naming in the `package.json` > `version` field. I was hoping to release this package with a that piggybacks on the original Slick repo's version number (1.8.1), but that does not seem possible now.

Instead I'll go ahead and use the version number `1.0.0`, and indicate which Slick version this was forked from in the README.

**Comment by jasonwebb** [comment]
**accessible-slick is now officially released!!**

I had to do a bit of fussing to get the publish workflow Action to work, and learned a couple new Git tidbits along the way. Unfortunately I had to increment the version number because the package was prematurely published to NPM while I was fussing around, and NPM does not allow reuse or deletion of version numbers. 

You can now grab this package and start using it right away the following ways:

* Install the package via NPM with the command `npm install accessible-slick`. See the [package page](https://www.npmjs.com/package/@accessible360/accessible-slick) for more.
* [Download a zip file with the repo contents by going to the Releases section of this repo.](https://github.com/Accessible360/accessible-slick/releases)
