### ISSUE TITLE
HTML Structure

### ISSUE THREAD

**Issue by vanessalh** [Accessible360/accessible-slick#30]
Hello,
The carousel should have a different markup structure. Each carousel item should be a list item inside an un-ordered element ul/li. 
```
<ul class="slick-track">
  <li class="slick-slide></li>
  <li class="slick-slide></li>
  <li class="slick-slide></li>
</ul>
```
Currently, just using div is an error for the accessibility recommandations.
Thanks a lot.

**Comment by jasonwebb** [comment]
Hi @vanessalh! In our testing here at Accessible360 with native screen reader users, we have found that this doesn't quite work out in practice. 

Screen readers will typically announce the total number of list items in a list whenever a user reaches it, but it will not count list items which are hidden in the accessibility tree. So when non-visible slides are properly hidden (as we do in accessible-slick using `aria-hidden="true"`), screen readers will only announce the number of _visible_ slides, not the true _total_ number of slides, leading to a confusing user experience. Instead we use an `aria-label` on each slide's wrapper to indicate the true total number of slides and each slide's position in the set (for example, `aria-label="slide 2 of 8"`). 

This is consistent with the technique used by the W3C's WAI-ARIA working group in their WAI-ARIA Authoring Practices 1.1 guide code sample found here: https://www.w3.org/TR/wai-aria-practices-1.1/examples/carousel/carousel-1.html
