### ISSUE TITLE
Browser resize processor issue?

### ISSUE THREAD

**Issue by mattpaz** [Accessible360/accessible-slick#37]
When using accessible slick and I resize my browser window (on macOS Big Sur) or emulate different screensizes via the device toolbar via dev tools, browsers take more than 100% of CPU (using Chrome, Safari and FF).  As it happens so quickly, I wasn't able to determine the root cause.  Eventually, they just die.  If I switch back to a kenwheeler/slick implementation using the same config, I don't experience the same issue.

I'd be interested in understanding if others are experiencing the same/similar issue?

Note, I'm unable to reproduce this condition at ... 
https://accessible360.github.io/accessible-slick/
... so, I expect the behavior stems from something else interacting w/ slick on the site where I was testing it.  Just odd that I couldn't reproduce it with similar config for vanilla slick.

Was just hoping someone else might have some thoughts.

**Comment by jasonwebb** [comment]
Hey @mattpaz! I have not experienced this myself, or heard of this happening, but that's not to say it isn't a thing. The accessible-slick package really just peppers in changes to ARIA attributes, text, and styling at key times, but I don't think anything was changed with the logic around responsive breakpoints. 

If you're able to replicate this in an isolated test case, I'd be happy to check it out!

**Comment by mattpaz** [comment]
10-4.  I'll close this for now and circle back with additional supporting information when I've got a chance to dive deeper.

I have a feeling there may be some race condition occurring somewhere with something else involving a11y tweaks that I'd been pursuing.  Will advise if / when I identify anything more substantive.

Thanks again.
Matt

**Comment by mattpaz** [comment]
Finally figured it out.  It seems to have been an issue with a solution I was trying to use for an accordion.  
It was roughly inspired by this ...
https://codepen.io/Bizo_dam/pen/KKzxMEq

I haven't dug deeply into it, but I suspect it had something to do with some type of scoping issue -- possibly something related to preventing key stroke defaults, but not sure why it would have manifested this way on resize. In any event, just wanted to close the loop and confirm that, by itself, there does not seem to be an issue with accessible-slick and resizing.
