### ISSUE TITLE
Pause button should not be there if only one item

### ISSUE THREAD

**Issue by jpyrat** [Accessible360/accessible-slick#47]
Hi,

I use slick with a CMS that insert the slick slider with 
`autoplay: true`

Sometimes, there is only 1 slide to display.
In this case, the play/pause button is useless and confusing.

**Comment by setsqr** [comment]
+1 on this. 

The default behaviour for Slick seems to be that the prev/next buttons and pagination dots mark-up is only injected into the DOM when needed and removed when it's not. It would be great if the pause/play button followed the same logic as there doesn't seem to be a good way of targeting its display via just CSS.

**Comment by supersonic1999** [comment]
agree also
