### ISSUE TITLE
Invalid cursor option in CSS

### ISSUE THREAD

**Issue by dwhiterei** [Accessible360/accessible-slick#50]
On line 30 of slick.scss, there is the following declaration: `cursor: hand`

Technically, `hand` is not one of the allowable options for `cursor` (see https://developer.mozilla.org/en-US/docs/Web/CSS/cursor). This should probably be `grab` or `grabbing`.

**Comment by pratikbassi** [comment]
Fix merged into master and tested, will be in next minor release
