### ISSUE TITLE
Console log test messages should be removed.

### ISSUE THREAD

**Issue by EmmanuelZamudioTR** [Accessible360/accessible-slick#60]
There are some `console.log('test')` messages that should be removed, because those are popping out in our site. 

There are some logs like this on slick.js:
![image](https://user-images.githubusercontent.com/86264906/156623685-2bd9b4e2-a31a-4075-afb7-df6ac684bf47.png)

**Comment by EmmanuelZamudioTR** [comment]
> @EmmanuelZamudioTR Are you sure you're using the latest bundle? I can't find this in the source code

It's not on master branch, it's on the latest [release tag v1.0.1](https://github.com/Accessible360/accessible-slick/blob/v1.0.1/slick/slick.js), so I think you'll need to launch another one with the last master updates. 

Here it is: 
![image](https://user-images.githubusercontent.com/86264906/158436540-9e66d65e-2eff-4a02-9d4b-48ae67893369.png)

**Comment by christopherdarling** [comment]
should be resolved by https://github.com/Accessible360/accessible-slick/issues/48 then

**Comment by EmmanuelZamudioTR** [comment]
> should be resolved by #48 then

Do you have a tentative date for your next release?

**Comment by christopherdarling** [comment]
I don't own this repo, just helping out in some of the bug reports.

**Comment by pratikbassi** [comment]
Fix merged into master, will be in the next minor release

**Comment by cojaco** [comment]
Is it planned to remove the console.log messages also from the npm package?
